---
name: Bug Report
description: Something done broke! Tell us about it!
labels: ["bug", "triage"]
assignees:
  - q
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect?
      description: What did you expect to happen?
      placeholder: Tell us what you were expecting!
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: What actualliy happened?
      description: Tell us happened!
      placeholder: Tell us what you actually see!
    validations:
      required: true
  - type: input
    id: demo
    attributes:
      label: Video demo
      description: Using your favourite screen recording tool, please share a video that shows us the steps you took to encounter the bug. Including your narration in the video is helpful.
      placeholder: http://...
    validations:
      required: false
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: What impact does this bug have on users?
      options:
        - High
        - Low
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: Should this be fixed now or can it be done later?
      options:
        - Now
        - Later
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - UC
        - Samsung Internet
        - Chromium & Derivitives
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      multiple: true
      options:
        - Windows
        - Mac
        - Linux
        - iOS
        - Android
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If possible, please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://geek.zone/code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true